//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Assets.Localisation {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MarmaladeLauncher.Common.Assets.Localisation.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Generic_OK {
            get {
                return ResourceManager.GetString("Generic.OK", resourceCulture);
            }
        }
        
        public static string Generic_Cancel {
            get {
                return ResourceManager.GetString("Generic.Cancel", resourceCulture);
            }
        }
        
        public static string Generic_Yes {
            get {
                return ResourceManager.GetString("Generic.Yes", resourceCulture);
            }
        }
        
        public static string Generic_No {
            get {
                return ResourceManager.GetString("Generic.No", resourceCulture);
            }
        }
        
        public static string Generic_Save {
            get {
                return ResourceManager.GetString("Generic.Save", resourceCulture);
            }
        }
        
        public static string Generic_Close {
            get {
                return ResourceManager.GetString("Generic.Close", resourceCulture);
            }
        }
        
        public static string Generic_Browse {
            get {
                return ResourceManager.GetString("Generic.Browse", resourceCulture);
            }
        }
        
        public static string Application_Title {
            get {
                return ResourceManager.GetString("Application.Title", resourceCulture);
            }
        }
        
        public static string Toolbar_Projects {
            get {
                return ResourceManager.GetString("Toolbar.Projects", resourceCulture);
            }
        }
        
        public static string Toolbar_Installations {
            get {
                return ResourceManager.GetString("Toolbar.Installations", resourceCulture);
            }
        }
        
        public static string Toolbar_Settings {
            get {
                return ResourceManager.GetString("Toolbar.Settings", resourceCulture);
            }
        }
        
        public static string Projects_Header {
            get {
                return ResourceManager.GetString("Projects.Header", resourceCulture);
            }
        }
        
        public static string Projects_NoProjectsWarning {
            get {
                return ResourceManager.GetString("Projects.NoProjectsWarning", resourceCulture);
            }
        }
        
        public static string Installations_Header {
            get {
                return ResourceManager.GetString("Installations.Header", resourceCulture);
            }
        }
        
        public static string Installations_NoInstallsWarning {
            get {
                return ResourceManager.GetString("Installations.NoInstallsWarning", resourceCulture);
            }
        }
        
        public static string Installations_MissingExecutable {
            get {
                return ResourceManager.GetString("Installations.MissingExecutable", resourceCulture);
            }
        }
        
        public static string Installations_Remove {
            get {
                return ResourceManager.GetString("Installations.Remove", resourceCulture);
            }
        }
        
        public static string Installations_Settings {
            get {
                return ResourceManager.GetString("Installations.Settings", resourceCulture);
            }
        }
        
        public static string Installations_Launch {
            get {
                return ResourceManager.GetString("Installations.Launch", resourceCulture);
            }
        }
        
        public static string Installations_Locate {
            get {
                return ResourceManager.GetString("Installations.Locate", resourceCulture);
            }
        }
        
        public static string Installation_Locate_FilePicker {
            get {
                return ResourceManager.GetString("Installation.Locate.FilePicker", resourceCulture);
            }
        }
        
        public static string Installations_Install {
            get {
                return ResourceManager.GetString("Installations.Install", resourceCulture);
            }
        }
        
        public static string Installations_FilterDevBuilds {
            get {
                return ResourceManager.GetString("Installations.FilterDevBuilds", resourceCulture);
            }
        }
        
        public static string Installations_MissingExecutable_Prompt_Title {
            get {
                return ResourceManager.GetString("Installations.MissingExecutable.Prompt.Title", resourceCulture);
            }
        }
        
        public static string Installations_MissingExecutable_Prompt_Body {
            get {
                return ResourceManager.GetString("Installations.MissingExecutable.Prompt.Body", resourceCulture);
            }
        }
        
        public static string Modal_NewInstall_NewInstall {
            get {
                return ResourceManager.GetString("Modal.NewInstall.NewInstall", resourceCulture);
            }
        }
        
        public static string Modal_NewInstall_NoAvailableInstalls {
            get {
                return ResourceManager.GetString("Modal.NewInstall.NoAvailableInstalls", resourceCulture);
            }
        }
        
        public static string Modal_NewInstall_DownloadingPrompt {
            get {
                return ResourceManager.GetString("Modal.NewInstall.DownloadingPrompt", resourceCulture);
            }
        }
        
        public static string Modal_NewInstall_SelectPrompt {
            get {
                return ResourceManager.GetString("Modal.NewInstall.SelectPrompt", resourceCulture);
            }
        }
        
        public static string Modal_NewInstall_Install {
            get {
                return ResourceManager.GetString("Modal.NewInstall.Install", resourceCulture);
            }
        }
        
        public static string Modal_Installation_Settings {
            get {
                return ResourceManager.GetString("Modal.Installation.Settings", resourceCulture);
            }
        }
        
        public static string Modal_Installation_ExecutablePath {
            get {
                return ResourceManager.GetString("Modal.Installation.ExecutablePath", resourceCulture);
            }
        }
        
        public static string Modal_Installation_CommandLineArguments {
            get {
                return ResourceManager.GetString("Modal.Installation.CommandLineArguments", resourceCulture);
            }
        }
        
        public static string Modal_Installation_Uninstall {
            get {
                return ResourceManager.GetString("Modal.Installation.Uninstall", resourceCulture);
            }
        }
        
        public static string Modal_Installation_Uninstall_Prompt_Title {
            get {
                return ResourceManager.GetString("Modal.Installation.Uninstall.Prompt.Title", resourceCulture);
            }
        }
        
        public static string Modal_Installation_Uninstall_Prompt_Body {
            get {
                return ResourceManager.GetString("Modal.Installation.Uninstall.Prompt.Body", resourceCulture);
            }
        }
        
        public static string Settings_Header {
            get {
                return ResourceManager.GetString("Settings.Header", resourceCulture);
            }
        }
        
        public static string Settings_EngineSettings {
            get {
                return ResourceManager.GetString("Settings.EngineSettings", resourceCulture);
            }
        }
        
        public static string Settings_DefaultEngineInstallPath {
            get {
                return ResourceManager.GetString("Settings.DefaultEngineInstallPath", resourceCulture);
            }
        }
        
        public static string Settings_ResetPath {
            get {
                return ResourceManager.GetString("Settings.ResetPath", resourceCulture);
            }
        }
        
        public static string Settings_ResetPathTooltip {
            get {
                return ResourceManager.GetString("Settings.ResetPathTooltip", resourceCulture);
            }
        }
        
        public static string Settings_LauncherSettings {
            get {
                return ResourceManager.GetString("Settings.LauncherSettings", resourceCulture);
            }
        }
        
        public static string Settings_PostLaunchBehaviour {
            get {
                return ResourceManager.GetString("Settings.PostLaunchBehaviour", resourceCulture);
            }
        }
        
        public static string Settings_PostLaunch_KeepOpen {
            get {
                return ResourceManager.GetString("Settings.PostLaunch_KeepOpen", resourceCulture);
            }
        }
        
        public static string Settings_PostLaunch_Minimise {
            get {
                return ResourceManager.GetString("Settings.PostLaunch_Minimise", resourceCulture);
            }
        }
        
        public static string Settings_PostLaunch_Close {
            get {
                return ResourceManager.GetString("Settings.PostLaunch_Close", resourceCulture);
            }
        }
        
        public static string Settings_EnableDevBuilds {
            get {
                return ResourceManager.GetString("Settings.EnableDevBuilds", resourceCulture);
            }
        }
        
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings.Language", resourceCulture);
            }
        }
        
        public static string Settings_LanguagePartialSupport {
            get {
                return ResourceManager.GetString("Settings.LanguagePartialSupport", resourceCulture);
            }
        }
    }
}
