//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Assets.Localisation {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager(
                        "MarmaladeLauncher.Common.Assets.Localisation.Resources", 
                        typeof(Resources).Assembly
                    );
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Toolbar_Projects {
            get {
                return ResourceManager.GetString("Toolbar.Projects", resourceCulture);
            }
        }
        
        public static string Toolbar_Installations {
            get {
                return ResourceManager.GetString("Toolbar.Installations", resourceCulture);
            }
        }
        
        public static string Toolbar_Settings {
            get {
                return ResourceManager.GetString("Toolbar.Settings", resourceCulture);
            }
        }
        
        public static string Projects_Header {
            get {
                return ResourceManager.GetString("Projects.Header", resourceCulture);
            }
        }
        
        public static string Projects_NoProjectsWarning {
            get {
                return ResourceManager.GetString("Projects.NoProjectsWarning", resourceCulture);
            }
        }
        
        public static string Installations_Header {
            get {
                return ResourceManager.GetString("Installations.Header", resourceCulture);
            }
        }
        
        public static string Installations_NoInstallsWarning {
            get {
                return ResourceManager.GetString("Installations.NoInstallsWarning", resourceCulture);
            }
        }
        
        public static string Installations_Remove {
            get {
                return ResourceManager.GetString("Installations.Remove", resourceCulture);
            }
        }
        
        public static string Installations_Settings {
            get {
                return ResourceManager.GetString("Installations.Settings", resourceCulture);
            }
        }
        
        public static string Installations_Launch {
            get {
                return ResourceManager.GetString("Installations.Launch", resourceCulture);
            }
        }
        
        public static string Installations_Locate {
            get {
                return ResourceManager.GetString("Installations.Locate", resourceCulture);
            }
        }
        
        public static string Installations_Install {
            get {
                return ResourceManager.GetString("Installations.Install", resourceCulture);
            }
        }
        
        public static string Installations_FilterDevBuilds {
            get {
                return ResourceManager.GetString("Installations.FilterDevBuilds", resourceCulture);
            }
        }
        
        public static string Modal_Installation_Settings {
            get {
                return ResourceManager.GetString("Modal.Installation.Settings", resourceCulture);
            }
        }
        
        public static string Modal_Installation_ExecutablePath {
            get {
                return ResourceManager.GetString("Modal.Installation.ExecutablePath", resourceCulture);
            }
        }
        
        public static string Modal_Installation_CommandLineArguments {
            get {
                return ResourceManager.GetString("Modal.Installation.CommandLineArguments", resourceCulture);
            }
        }
        
        public static string Modal_Installation_Save {
            get {
                return ResourceManager.GetString("Modal.Installation.Save", resourceCulture);
            }
        }
        
        public static string Modal_Installation_Close {
            get {
                return ResourceManager.GetString("Modal.Installation.Close", resourceCulture);
            }
        }
        
        public static string Settings_Header {
            get {
                return ResourceManager.GetString("Settings.Header", resourceCulture);
            }
        }
        
        public static string Settings_EngineSettings {
            get {
                return ResourceManager.GetString("Settings.EngineSettings", resourceCulture);
            }
        }
        
        public static string Settings_DefaultEngineInstallPath {
            get {
                return ResourceManager.GetString("Settings.DefaultEngineInstallPath", resourceCulture);
            }
        }
        
        public static string Settings_BrowsePrompt {
            get {
                return ResourceManager.GetString("Settings.BrowsePrompt", resourceCulture);
            }
        }
        
        public static string Settings_ResetPath {
            get {
                return ResourceManager.GetString("Settings.ResetPath", resourceCulture);
            }
        }
        
        public static string Settings_ResetPathTooltip {
            get {
                return ResourceManager.GetString("Settings.ResetPathTooltip", resourceCulture);
            }
        }
        
        public static string Settings_LauncherSettings {
            get {
                return ResourceManager.GetString("Settings.LauncherSettings", resourceCulture);
            }
        }
        
        public static string Settings_PostLaunchBehaviour {
            get {
                return ResourceManager.GetString("Settings.PostLaunchBehaviour", resourceCulture);
            }
        }
        
        public static string Settings_PostLaunch_KeepOpen {
            get {
                return ResourceManager.GetString("Settings.PostLaunch_KeepOpen", resourceCulture);
            }
        }
        
        public static string Settings_PostLaunch_Minimise {
            get {
                return ResourceManager.GetString("Settings.PostLaunch_Minimise", resourceCulture);
            }
        }
        
        public static string Settings_PostLaunch_Close {
            get {
                return ResourceManager.GetString("Settings.PostLaunch_Close", resourceCulture);
            }
        }
        
        public static string Settings_EnableDevBuilds {
            get {
                return ResourceManager.GetString("Settings.EnableDevBuilds", resourceCulture);
            }
        }
        
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings.Language", resourceCulture);
            }
        }
        
        public static string Settings_LanguagePartialSupport {
            get {
                return ResourceManager.GetString("Settings.LanguagePartialSupport", resourceCulture);
            }
        }
        
        public static string Settings_SaveSettings {
            get {
                return ResourceManager.GetString("Settings.SaveSettings", resourceCulture);
            }
        }
        
        public static string Settings_CancelChanges {
            get {
                return ResourceManager.GetString("Settings.CancelChanges", resourceCulture);
            }
        }
    }
}
